### ISSUE TITLE
Removed from Google Play?

### ISSUE THREAD

**Issue by TaylanUB** [Thunderlight-Software/Zebra-Print-Service#1]
I'm guessing that this was taken down because it used "Zebra" in its name? Is it possible to add it back to the Google Play Store under a different name / without breaking any other rules?

Amazing project by the way. I can't understand why Zebra doesn't offer such a service... They have lots of complex apps but nothing that just uses the standard Android print system from what I can tell.

**Comment by GCrean** [comment]
I've removed it because i was getting alot of support requests. I really don't have the time to follow up on them and thought releasing the source code would be a better idea. I may release this again as now I'm getting requests for built binaries now. Seems I can't win.

**Comment by TaylanUB** [comment]
Ah ok, I won't bother you then. ;-)

As a thank you for your work: if you ever need to connect to an industrial
label printer directly (via TCP) instead of going through Android's
annoying printing subsystem, I wrote a blog post on how this can be done
with ZPL (Zebra Programming Language) to print arbitrary HTML:

https://taylan-kammer.blogspot.com/2020/12/print-html-android-zpl.html

ZPL has actually become a de facto standard among label printers so it's
supported by many more brands than just Zebra.

**Comment by GCrean** [comment]
I've just read your post, What a great article. I've forwarded it to a couple of my colleges also. As for the play store listing. I've republished it. At least I can get some download stats and see if it's being used or not.
