### ISSUE TITLE
Google Play store 

### ISSUE THREAD

**Issue by n3rdout** [Thunderlight-Software/Zebra-Print-Service#13]
Link is not working for the google play store. It doesn't show when searching manually either. Is there a way to install it manually without using the Play store? My firm relies on this print service for our mobile printers.

**Comment by reelsea** [comment]
Same here - has anyone found a solution? This has been extremely unreliable with android 11

**Comment by n3rdout** [comment]
> Same here - has anyone found a solution? This has been extremely unreliable with android 11

I ended up finding the last version and putting in a Google drive folder. That way I can install it on any device when I need to. It was a pain and I never got any reply from the devs. For me there is no workaround as Zebra has been zero help as well.

**Comment by reelsea** [comment]
Understood - I was able to deploy (we use an MDM to deliver) but can’t apply profiles for some reason. Trying to not have end users have to configure. Zebra has had same help to me as well. Sent from my iPhoneOn Jul 16, 2023, at 5:59 PM, n3rdout ***@***.***> wrote:﻿

Same here - has anyone found a solution? This has been extremely unreliable with android 11

I ended up finding the last version and putting in a Google drive folder. That way I can install it on any device when I need to. It was a pain and I never got any reply from the devs. For me there is no workaround as Zebra has been zero help as well.

**Comment by ltrudu** [comment]
Hi,
This is not an official project supported by Zebra.
It's a community project, so you won't get any support by Zebra on it.
You can check my fork and releases here:

**Comment by ltrudu** [comment]
https://github.com/ltrudu/Zebra-Print-Service

**Comment by JeroenVanOort** [comment]
Is there any change of getting this published to the Play Store? I understand that this (no longer) an official Zebra product and the applicationId might need to be changed, but that's it, right?

**Comment by Binary-Warrior** [comment]
Zebra asked me to remove this from the Play Store, I was also told that Zebra would be looking into supporting something soon.
